### ISSUE TITLE
Getting wrong saturation value

### ISSUE THREAD

**Issue by chioma91** [jnovack/homebridge-better-http-rgb#1]
Hi,
I'm successfully using the plugin and I can set the correct hue, saturation and brightness values to my arduino based device.
The problem is that when the plugin tries to get the light status, it gets the correct hue values but it gets 100% saturation, whatever it is: i.e.

```
[2016-06-01 10:46:59] [Led RGB] _setRGB converting H:176 S:54 B:100 to RGB:75fff6 ...
[2016-06-01 10:46:59] [Led RGB] ... _setRGB() successfully set to #75fff6
[2016-06-01 10:47:05] [Led RGB] power is currently ON
[2016-06-01 10:47:06] [Led RGB] ... hue is currently 176
[2016-06-01 10:47:06] [Led RGB] ... saturation is currently 100
```

I'm pretty sure that the issue is not related to my device, because I can monitor it, and when homebridge asks for the light status, the device sends the correct value (i.e. 75fff6). I thinks it's just a problem in the conversion from hex to HSV in the plugin.

I've also noticed that every time the plugin, asking for hue and saturation, it asks the same thing (the hex color) twice. Is it possibile to avoid it?

thanks

This my config

```
{
        "bridge": {
                "name": "Homebridge",
                "username": "CC:22:3D:E3:CE:30",
                "port": 51826,
                "pin": "031-45-154"
        },

        "description": "Bridge di Piazza Belluno",

        "platforms": [
                 {
                  "platform" : "HomeBridgeControllerLink"
                 }
        ],

        "accessories": [{
                        "accessory": "HTTP-RGB",
                        "name": "Led RGB",

                        "switch": {
                                "powerOn": "http://192.168.1.100/H",
                                "powerOff": "http://192.168.1.100/L",
                                "status": "http://192.168.1.100/status"
                        },
                        "color": {
                                "url": "http://192.168.1.100/set/%s",
                                "status": "http://192.168.1.100/set",
                                "brightness": true
                        }
                }
        ]
}
```

**Comment by jnovack** [comment]
> when homebridge asks for the light status, the device sends the correct value (i.e. 75fff6). I thinks it's just a problem in the conversion from hex to HSV in the plugin.

It's not HSV.  Apple's color wheel uses HSL. So converting `75FFF6` to HSL yields 100% Saturation.  I struggled with that too.

> I've also noticed that every time the plugin, asking for hue and saturation, it asks the same thing (the hex color) twice. Is it possibile to avoid it?

No, because of the evented nature of Javascript.  I cannot accurately fire off responses with callbacks while keeping the values as a state.
