### ISSUE TITLE
Problem if I want more than 1 accessory.

### ISSUE THREAD

**Issue by marcdebruin** [jnovack/homebridge-better-http-rgb#13]
I have a problem with my config file of my homebridge system when i do 1 accessory do it all but if I want to add 1 or more accessorys I get an error, I tested the code at: (https://jsonformatter.curiousconcept.com) and then I get an error message, can anyone help me.

{
   "bridge": {
      "name": "Slaapkamer",
      "username": "CC:22:3D:E3:CE:30",
      "port": 51826,
      "pin": "031-45-154"
   },

   "description": "Homebridge-Systeem",

    "accessories": [
                    {
        "accessory": "HTTP-RGB",
        "name": "Lamp-1",
        "switch": {
        "powerOn": "http://192.168.178.21/socket1On",
        "powerOff": "http://192.168.178.21/socket1Off"   
   },
   {
        "accessory": "HTTP-RGB",
        "name": "Lamp-1",
        "switch": {
        "powerOn": "http://192.168.178.21/socket1On",
        "powerOff": "http://192.168.178.21/socket1Off"
   }],

   "platforms": []

}

**Comment by jnovack** [comment]
They are both the same.  I believe the "name" has to be unique.

**Comment by marcdebruin** [comment]
No man the code say that there is a problem in de code

Verzonden vanuit Mail<https://go.microsoft.com/fwlink/?LinkId=550986> voor Windows 10

________________________________
Van: Justin J. Novack <notifications@github.com>
Verzonden: Monday, November 6, 2017 7:36:04 PM
Aan: jnovack/homebridge-better-http-rgb
CC: marcdebruin; Author
Onderwerp: Re: [jnovack/homebridge-better-http-rgb] Problem if I want more than 1 accessory. (#13)


They are both the same. I believe the "name" has to be unique.

**Comment by jnovack** [comment]
Cool man, fix "de code" then.
