### ISSUE TITLE
How can i change the default preset color palette in the Home app?

### ISSUE THREAD

**Issue by Uraforclain** [jnovack/homebridge-better-http-rgb#22]
First and foremost thanks for this wonderful plugin!

I would love to change the 6 preset colors. Where is the file to edit this? Cause i cant find it in index.js. 

:)

**Comment by jnovack** [comment]
That's because it is not in index.js.  That's not a function of this software.

**Comment by Uraforclain** [comment]
May i ask where do i find it then?

**Comment by jnovack** [comment]
Whichever Home application you are using.
