### ISSUE TITLE
No example of embedded firmware

### ISSUE THREAD

**Issue by JoniSykes** [jnovack/homebridge-better-http-rgb#7]
Hi! Thanks so much for this plugin! This looks like just what I need :)
I'm currently having issues using outdated examples of the old homebridge dynamic accessory architecture. I haven't been able to find a good example of a new plugin until I saw this.

However, I'd better understand how this is used if I could see some example firmware for whatever is controlling the LED. 

For example I have a Spark Core (now called Particle Photon) and an Arduino and an RPi. I assume any of these could act as controllers.

I'm using a modified (working) version of this on my Core:
https://github.com/nikita-leonov/particleio-homekit/blob/master/hue-light-simulator.ino
But as I mentioned I'd need to write a whole new plugin for that. So instead I'd like to modify the endpoints to work with your plugin and that is where I'm stuck.

Could you provide (even if it's just pseudocode) an example of the receiving API and what it does. 
Something like:
Colour Api - /set:
Takes in json object:
```
{
    "hue": "360",
    "brightness": "100",
    "saturation": "100"
}
```
Method set then converts to RBG space and writes colour to LED.

Make sense?

I'd be happy to provide my working version of the firmware if that helps provide a base example for you to modify? I can even test it too once modified.
Failing that just some pseudocode would be fine.

Thanks.

**Comment by jnovack** [comment]
> I'm currently having issues using outdated examples of the old homebridge dynamic accessory architecture. I haven't been able to find a good example of a new plugin until I saw this.

I haven't played with homebridge in a while, is this "outdated"?

> Could you provide (even if it's just pseudocode) an example of the receiving API and what it does.

This isn't the receiving API.  The receiving API is defined by the application itself!  Those are just variables.

This plugin takes the input from your homebridge server and HITS a receiving API based on the input.  You clicked "ON" in your application?  This plugin will hit "http://localhost/api/v1/on".  You want to hit "http://www.google.com/" instead? It can! (won't do anything obviously)

The project for the API server is here: https://github.com/jnovack/http-led-controller

**Comment by JoniSykes** [comment]
Thanks for the speedy reply!!
I don't think your work is outdated no, I simply meant other examples I had tried were outdated.

I'm aware that this is not the receiving API, in fact this is the bridge between homebridge and your accessory. 
The problem I wanted some guidance with is the relationship between the plugin and the accessory. 

Let me give you an example:
My Spark Core has code in it to set the powerstate of an RGB led. This is exposed as a cloud function at /powerstate. 
To make this work I imagine I would need to change your plugin to hit that instead of hitting two separate endpoints for 'On' and 'Off'.
Similarly I have separate endpoints for Hue, Saturation and Brightness but the plugin is only calling one endpoint for 'colour'.

I understand that what I want the plugin to do is determined by what I want my accessory to do, but I did think it would be nice if you explained what is happening with your accessories once the plugin has called your endpoint "http://localhost/api/v1/on". 

That would assist me in changing my own code to work WITH yours, as opposed to leaving my accessory unchanged and reworking the plugin to suit my needs. 

Thanks,
Joni

**Comment by jnovack** [comment]
> To make this work I imagine I would need to change your plugin to hit that instead of hitting two separate endpoints for 'On' and 'Off'.

Correct.  You can modify the code within `setPowerState()` to include a body of JSON you build, or even add authentications.

> Similarly I have separate endpoints for Hue, Saturation and Brightness but the plugin is only calling one endpoint for 'colour'.

Since this is an RGB plugin, and Homebridge natively uses HSB, you can get rid of the `_setRGB()` function entirely and call each H, S or B in their respective functions!

The `_setRGB()` "hack" is meant to combine and convert the H, S and B for RGB listeners.  You can just make the HTTP call within `setHue()`, etc.

The reason for the aggregate function (and it's ugly hack of color handling) is due to the async nature of Homebridge and HSB.  When you click the color wheel on the application within a Homebridge app, it sends to the server MULTIPLE calls depending on what you changed.

If you went from a H:100, S:50, B:50 to H:100, S:25, B:75, then the server receives two calls, one for S:25 and one for B:75.   That's why I always have to remember the state, as the "B:75" chunklet does not contain the S:25, so I can't just mess with the brightness.  You may not need any of that wizardry for your application.

**Comment by JoniSykes** [comment]
That makes a tonne more sense. Thanks for the explanation :)

It seems that the way to go is to make my own plugin. I've tried to avoid that until now, but it seems to make the most sense. 
Particularly if I need HSB for my lights. I may go on to add sensors and such too.

Do you know of any good resources for how plugins are written? Or any advice? 
I started with the basic http example but it's still poorly documented by homebridge.

Thanks again,
Joni

**Comment by jnovack** [comment]
This was designed to be an example plugin that you could modify.

I don't know what your requirements are, but from the conversations thus far, I don't see why you can't just modify this plugin.  Remove the unneeded bits, add your custom bits, keep the structure.

**Comment by jnovack** [comment]
Hope everything is going well, I was expecting to find a `jonisykes/homebridge-even-better-http-rgb/` plugin. 

Good luck!
