### ISSUE TITLE
Color being set twice when choosing a color

### ISSUE THREAD

**Issue by ludvigeriksson** [jnovack/homebridge-better-http-rgb#8]
Almost every time choosing a color in HomeKit on my phone, homebridge sets it twice, with the second being very wrong.

<img width="877" alt="screen shot 2017-01-27 at 16 15 05" src="https://cloud.githubusercontent.com/assets/7629496/22375835/f8a014ca-e4ab-11e6-9cda-ca125aa8f29e.png">

This is the configuration:

    {
        "accessory": "HTTP-RGB",
        "name": "RGB Led Strip",

        "switch": {
            "status": "http://localhost/api/v1/status",
            "powerOn": "http://localhost/api/v1/on",
            "powerOff": "http://localhost/api/v1/off"
          },

        "color": {
            "status": "http://localhost/api/v1/color",
            "url": "http://localhost/api/v1/color?color=%s"
        }
    }

**Comment by ludvigeriksson** [comment]
The problem seems to be that _setRGB() is called in the wrong order sometimes. As in the example above, 000dff (the correct color) is calculated last, but _setRGB() for it is called first. It then gets overwritten by the second incorrect color.

**Comment by RickWieman** [comment]
`_setRGB()` performs asynchronous http requests, so there is (unfortunately) no guarantee on the order of execution/completion... I've experienced the same issue, and I noticed that (in my case) `setHue` and `setSaturation` are always invoked both, so I simply replaced the `this._setRGB(callback)` call in the `setSaturation` with `callback()` to eliminate one http call; this is of course a workaround, but for me, that works.
I'm definitely interested to see a real solution for this issue 😊

**Comment by jnovack** [comment]
This is an issue with the asynchronous model of Javascript, I tried to handle it the best I could in `_setRGB()`, unfortunately it does not always work.

**Comment by andreypopov** [comment]
I have the same issue. I want to find the way how to make only one request on "color change"
Now, when I change color, there are 3 requests: power on, brightness 100% and color (I joined hue and saturation)

**Comment by andreypopov** [comment]
Ok, finally I made it. One common event for set all characteristics. I need few days to test it_)!

**Comment by JH1616** [comment]
i had the same problem, because I use a web server that performs asynchronous http requests (much faster with scenes).
i fix it by returning hue and saturation directly. Afterwards I save all stuff and calculate rgb.

thanks for the perfect plugin!

**Comment by mgibeau** [comment]
Seems like #12 fixed it, would you be able to publish a new version to npm? Thanks!

**Comment by jnovack** [comment]
#mybad
